import { NextRequest, NextResponse } from "next/server";

export interface AiAnbefalingResponse {
  tip: string | null;
  unavailable: boolean;
  /** true = generated by LLM; false = API key missing or error */
  isAi: boolean;
}

export async function GET(req: NextRequest) {
  const { searchParams } = req.nextUrl;
  const routeName = searchParams.get("route") ?? "";
  const vanskelighet = searchParams.get("vanskelighet") ?? "";
  const distanceKm = searchParams.get("distanceKm") ?? "";
  const season = searchParams.get("season") ?? "";

  const apiKey = process.env.OPENAI_API_KEY;
  if (!apiKey) {
    return NextResponse.json<AiAnbefalingResponse>({
      tip: null,
      unavailable: true,
      isAi: false,
    });
  }

  const prompt = `Du er en erfaren norsk turguide. Gi et kort, konkret tips (2-3 setninger) for å forberede seg til denne turen. Vær spesifikk på utstyr eller vær.

Tur: ${routeName}
Vanskelighet: ${vanskelighet}
Avstand: ${distanceKm} km
Sesong: ${season}

Svar kun med selve tipset på norsk, ingen introduksjon eller avslutning.`;

  try {
    const res = await fetch("https://api.openai.com/v1/chat/completions", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        Authorization: `Bearer ${apiKey}`,
      },
      body: JSON.stringify({
        model: "gpt-4o-mini",
        messages: [{ role: "user", content: prompt }],
        max_tokens: 150,
        temperature: 0.7,
      }),
    });

    if (!res.ok) {
      return NextResponse.json<AiAnbefalingResponse>({
        tip: null,
        unavailable: true,
        isAi: false,
      });
    }

    const data = await res.json();
    const tip: string | null =
      data.choices?.[0]?.message?.content?.trim() ?? null;

    return NextResponse.json<AiAnbefalingResponse>({
      tip,
      unavailable: false,
      isAi: true,
    });
  } catch {
    return NextResponse.json<AiAnbefalingResponse>({
      tip: null,
      unavailable: true,
      isAi: false,
    });
  }
}
